theme: jekyll-theme-architect
title: Nospof Blog
description: Enter the nospof universe
include:
   - _pages
paginate: 5 # amount of posts to show
paginate_path: /page:num/
plugins:
   - jekyll-include-cache
   - jekyll-seo-tag